/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sm;

import com.github.sarxos.webcam.Webcam;
import com.github.sarxos.webcam.WebcamPanel;
import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.Point;
import sm.ajpp.iu.Lienzo2DImagen;

/**
 *
 * @author ajpelaez
 */
public class InternalWindowCamera extends InternalWindow {
    private Webcam camera = null;
    
    public InternalWindowCamera(MainWindow parentWindow, Point location) {
        super(parentWindow, location);
        initComponents();
        camera = Webcam.getDefault();
        if (camera != null) {
            Dimension resoluciones[] = camera.getViewSizes();
            Dimension maxRes = resoluciones[resoluciones.length-1];
            camera.setViewSize(maxRes);
            this.setPreferredSize(maxRes);
            WebcamPanel areaVisual = new WebcamPanel(camera);
            if (areaVisual!= null) {
                areaVisual.setFitArea(false);
                visualPanel.add(areaVisual, BorderLayout.CENTER);
                pack();
            }
        }
    }
    
    public boolean containsCamera(){ return camera!=null;}
    
    public Webcam getCamera(){
        return this.camera;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        visualPanel = new javax.swing.JPanel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setMinimumSize(new java.awt.Dimension(400, 400));
        setPreferredSize(new java.awt.Dimension(400, 400));

        visualPanel.setMinimumSize(new java.awt.Dimension(400, 400));
        visualPanel.setPreferredSize(new java.awt.Dimension(400, 400));
        visualPanel.setLayout(new java.awt.BorderLayout());
        getContentPane().add(visualPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel visualPanel;
    // End of variables declaration//GEN-END:variables

    @Override
    Lienzo2DImagen getLienzo() {
        throw new UnsupportedOperationException("Not supported yet.");
    }
}
