/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sm;

import java.awt.Point;
import java.io.File;
import sm.ajpp.iu.Lienzo2DImagen;
import uk.co.caprica.vlcj.component.EmbeddedMediaPlayerComponent;
import uk.co.caprica.vlcj.player.MediaPlayer;
import uk.co.caprica.vlcj.player.MediaPlayerEventAdapter;
import uk.co.caprica.vlcj.player.embedded.EmbeddedMediaPlayer;

/**
 *
 * @author ajpelaez
 */
public class InternalWindowVLCPlayer extends InternalWindow {
    private EmbeddedMediaPlayer vlcplayer = null;
    private File mediaFile;
    
    
    private class VideoListener extends MediaPlayerEventAdapter {
        @Override
        public void finished(MediaPlayer mediaPlayer) {
            playButton.setEnabled(true);
        }
    }
    
    public InternalWindowVLCPlayer(MainWindow parentWindow, Point location) {
        super(parentWindow, location);
        initComponents();
    }
    
    public void setVideoContent(File mediaFile){
        this.mediaFile = mediaFile;
        EmbeddedMediaPlayerComponent aVisual = new EmbeddedMediaPlayerComponent();
        globalPanel.add(aVisual,java.awt.BorderLayout.CENTER);
        vlcplayer = aVisual.getMediaPlayer();
        vlcplayer.addMediaPlayerEventListener(new VideoListener());
    }
    
    public void play() {
        if (vlcplayer != null) {
            if(vlcplayer.isPlayable()){
                vlcplayer.play();
            } else {    
                vlcplayer.playMedia(mediaFile.getAbsolutePath());
            }
            playButton.setEnabled(false);
        }
    }
    
    public void stop() {
        if (vlcplayer != null) {
            if (vlcplayer.isPlaying()) {
                vlcplayer.pause();
            } else {
                vlcplayer.stop();
            }
        }
        playButton.setEnabled(true);
    }
    
    public boolean containsVideo(){ return vlcplayer!=null;}
    
    public EmbeddedMediaPlayer getVLCPlayer(){
        return vlcplayer;
    }
    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        globalPanel = new javax.swing.JPanel();
        buttonsPanel = new javax.swing.JPanel();
        playButton = new javax.swing.JButton();
        stopButton = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setMinimumSize(new java.awt.Dimension(400, 400));
        setPreferredSize(new java.awt.Dimension(400, 400));

        globalPanel.setLayout(new java.awt.BorderLayout());

        playButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sm/iconos/Play.png"))); // NOI18N
        playButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playButtonActionPerformed(evt);
            }
        });
        buttonsPanel.add(playButton);

        stopButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sm/iconos/Stop.png"))); // NOI18N
        stopButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stopButtonActionPerformed(evt);
            }
        });
        buttonsPanel.add(stopButton);

        globalPanel.add(buttonsPanel, java.awt.BorderLayout.SOUTH);

        getContentPane().add(globalPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void stopButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stopButtonActionPerformed
        this.stop();
    }//GEN-LAST:event_stopButtonActionPerformed

    private void playButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playButtonActionPerformed
        this.play();
    }//GEN-LAST:event_playButtonActionPerformed


    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel buttonsPanel;
    private javax.swing.JPanel globalPanel;
    private javax.swing.JButton playButton;
    private javax.swing.JButton stopButton;
    // End of variables declaration//GEN-END:variables

    @Override
    Lienzo2DImagen getLienzo() {
        throw new UnsupportedOperationException("Not supported yet.");
    }
}
